import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Debto",
  description: "Terms and conditions for using Debto's AI-powered debt management platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="bg-[#1B2A4A] text-white py-16">
        <div className="max-w-3xl mx-auto px-6">
          <Link href="/" className="inline-flex items-center gap-2 text-white/70 hover:text-white mb-6 text-sm transition-colors">
            <span className="material-symbols-rounded text-lg">arrow_back</span>
            Back to Debto
          </Link>
          <h1 className="text-4xl font-bold">Terms of Service</h1>
          <p className="text-white/60 mt-2">Last updated: March 12, 2026</p>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-gray prose-lg">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Debto (&quot;the Platform&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.
        </p>

        <h2>2. Description of Service</h2>
        <p>Debto provides:</p>
        <ul>
          <li>CIBIL credit report fetching and visualization (via Decentro APIs)</li>
          <li>AI-powered debt analysis and repayment strategy recommendations</li>
          <li>Financial calculators (extra payments, balance transfers, consolidation)</li>
          <li>Expert consultation booking and payment processing</li>
        </ul>

        <h2>3. Eligibility</h2>
        <p>You must be:</p>
        <ul>
          <li>At least 18 years of age</li>
          <li>An Indian resident with a valid PAN and Aadhaar</li>
          <li>The lawful owner of the financial accounts you submit for analysis</li>
        </ul>

        <h2>4. Account Registration</h2>
        <p>You agree to provide accurate, current information during registration. You are responsible for maintaining the security of your account credentials and for all activities under your account.</p>

        <h2>5. KYC Verification</h2>
        <p>To use our credit report and analysis features, you must complete KYC verification by providing your PAN and Aadhaar. By doing so, you:</p>
        <ul>
          <li>Confirm the identity documents belong to you</li>
          <li>Authorize Debto to verify your PAN via Decentro</li>
          <li>Provide explicit consent before any credit bureau inquiry</li>
        </ul>

        <h2>6. Credit Report Access</h2>
        <p>
          Debto fetches your CIBIL credit report through Decentro as a &quot;soft inquiry.&quot; This does not impact your credit score. You must provide explicit consent before each fetch. Reports are cached for 24 hours and auto-deleted after 90 days per DPDP Act requirements.
        </p>

        <h2>7. AI Analysis Disclaimer</h2>
        <p><strong>Important:</strong> The AI-generated analysis and recommendations are for informational purposes only and do not constitute financial advice. All financial numbers are computed using deterministic algorithms. The narrative text is generated by AI (Anthropic Claude) and may contain general guidance.</p>
        <ul>
          <li>Debto is not a registered financial advisor (SEBI/RBI)</li>
          <li>We recommend consulting a certified financial planner for major financial decisions</li>
          <li>Past performance projections are estimates and not guaranteed</li>
        </ul>

        <h2>8. Consultation Services</h2>
        <p>Expert consultations are provided by independent financial advisors. Debto facilitates the booking and payment but is not responsible for the advice provided during consultations. Refund policies are subject to individual advisor terms.</p>

        <h2>9. Payments</h2>
        <p>All payments for consultations are processed securely via Razorpay. Prices are listed in Indian Rupees (INR) and include applicable GST (18%). By making a payment, you agree to Razorpay&apos;s terms of service.</p>

        <h2>10. Prohibited Uses</h2>
        <p>You may not:</p>
        <ul>
          <li>Use someone else&apos;s identity documents for KYC</li>
          <li>Attempt to circumvent rate limits or security measures</li>
          <li>Scrape, reverse-engineer, or redistribute Debto&apos;s analysis algorithms</li>
          <li>Use the platform for any unlawful purpose</li>
        </ul>

        <h2>11. Limitation of Liability</h2>
        <p>Debto provides the platform &quot;as is&quot; without warranty. We are not liable for financial losses resulting from decisions made based on our analysis or recommendations. Our total liability shall not exceed the fees paid by you in the preceding 12 months.</p>

        <h2>12. Termination</h2>
        <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time from Settings → Data & Privacy.</p>

        <h2>13. Governing Law</h2>
        <p>These terms are governed by the laws of India. Disputes shall be subject to the exclusive jurisdiction of courts in Mumbai, Maharashtra.</p>

        <h2>14. Contact</h2>
        <p>For questions about these terms: <a href="mailto:legal@debto.in">legal@debto.in</a></p>
      </main>

      <footer className="border-t border-gray-200 py-8">
        <div className="max-w-3xl mx-auto px-6 flex gap-6 text-sm text-gray-500">
          <Link href="/privacy" className="hover:text-[#1B2A4A] transition-colors">Privacy Policy</Link>
          <Link href="/cookie-policy" className="hover:text-[#1B2A4A] transition-colors">Cookie Policy</Link>
          <Link href="/" className="hover:text-[#1B2A4A] transition-colors">Home</Link>
        </div>
      </footer>
    </div>
  );
}
